### ISSUE TITLE
启动时出现报错

### ISSUE THREAD

**Issue by ChuxiaRenwu** [SweetSmellFox/MFAWPF#14]
MFA 遇到了问题
“对类型“MFAWPF.Views.MainWindow”的构造函数执行符合指定的绑定约束的调用时引发了异常。”，行号为“14”，行位置为“24”。
Unable to load DLL 'MaaToolkit' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
详细信息
System.Windows.Markup.XamlParseException: “对类型“MFAWPF.Views.MainWindow”的构造函数执行符合指定的绑定约束的调用时引发了异常。”，行号为“14”，行位置为“24”。
 ---> System.DllNotFoundException: Unable to load DLL 'MaaToolkit' or one of its dependencies: 动态链接库(DLL)初始化例程失败。 (0x8007045A)
   at MaaFramework.Binding.Interop.Native.MaaToolkit.<MaaToolkitConfigInitOption>g____PInvoke|12_0(Byte* __userPath_native, Byte* __defaultJson_native)
   at MaaFramework.Binding.Interop.Native.MaaToolkit.MaaToolkitConfigInitOption(String userPath, String defaultJson)
   at MaaFramework.Binding.MaaToolkit.ConfigClass.InitOption(String userPath, String defaultJson)
   at MaaFramework.Binding.MaaToolkit..ctor(Boolean init, String userPath, String defaultJson)
   at MFAWPF.Views.MainWindow..ctor() in F:\RiderProjects\MFAWPF\MFAWPF\Views\MainWindow.xaml.cs:line 49
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SweetSmellFox** [comment]
更新一下VC++，https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by ChuxiaRenwu** [comment]
已经解决
![image](https://github.com/user-attachments/assets/ddbbfe2b-16ae-48ba-8310-26b1204cfe89)
