### ISSUE TITLE
Invalid value for AdbScreenCapMethods: 18446744073709551559

### ISSUE THREAD

**Issue by a16797** [SweetSmellFox/MFAWPF#33]
问题复现：
1.启动MFAWPF，正常连接模拟器，然后启动任务。关闭MFAWPF。
2.再次启动MFAWPF报错。

用MFAWPF.v1.2.1.2，不会报错，麻烦大佬们瞧瞧。

版本在这
https://github.com/MaaXYZ/M9A/releases/download/v2.3.1/M9A-win-x86_64-v2.3.1.zip
![image](https://github.com/user-attachments/assets/bbe0db02-3222-4cf5-b80c-30a788acadf1)

MFA 遇到了问题
Invalid value for AdbScreenCapMethods: 18446744073709551559
详细信息
System.ArgumentException: Invalid value for AdbScreenCapMethods: 18446744073709551559
   at MFAWPF.Utils.Converters.AdbScreencapMethodsConverter.ReadJson(JsonReader reader, Type objectType, AdbScreencapMethods existingValue, Boolean hasExistingValue, JsonSerializer serializer)
   at Newtonsoft.Json.JsonConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at MFAWPF.Views.MainWindow.TabControl_OnSelectionChanged(Object sender, SelectionChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by a16797** [comment]
"ScreencapMethods": 18446744073709551567
这个不会报错

**Comment by a16797** [comment]
[M9A-win-x86_64-v2.3.zip](https://github.com/user-attachments/files/17365512/M9A-win-x86_64-v2.3.zip)
[M9A-win-x86_64-v2.3.z01.zip](https://github.com/user-attachments/files/17365519/M9A-win-x86_64-v2.3.z01.zip)
[M9A-win-x86_64-v2.3.z02.zip](https://github.com/user-attachments/files/17365523/M9A-win-x86_64-v2.3.z02.zip)
文件太大传不了。去掉第二第三个文件后面的.zip

**Comment by SweetSmellFox** [comment]
修复了
