### ISSUE TITLE
任务列表空白

### ISSUE THREAD

**Issue by MuHei-del** [SweetSmellFox/MFAWPF#50]
![image](https://github.com/user-attachments/assets/242798f1-0505-4e6c-9a26-d1776f94c524)

**Comment by SweetSmellFox** [comment]
应该是interface.json错误，可以给一下mfa的log

**Comment by MuHei-del** [comment]
[2024-11-08.log](https://github.com/user-attachments/files/17673175/2024-11-08.log)

**Comment by APLaS-Plus** [comment]
+1，下载下来打开任务列表空白😭，日志如下：
2024-11-09 01:59:48.1333 ERROR System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\MFAWPF.v1.2.1.7\Resource\base\pipeline\sample.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at MFAWPF.Views.MainWindow.LoadTask() in F:\RiderProjects\MFAWPF\MFAWPF\Views\MainWindow.xaml.cs:line 270
2024-11-09 02:00:28.6737 ERROR System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\MFAWPF.v1.2.1.7\Resource\base\pipeline\sample.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at MFAWPF.Views.MainWindow.LoadTask() in F:\RiderProjects\MFAWPF\MFAWPF\Views\MainWindow.xaml.cs:line 270
2024-11-09 02:00:28.6786 INFO 正在载入资源
2024-11-09 02:00:28.8780 INFO 
2024-11-09 02:00:28.8780 INFO 正在初始化控制器
2024-11-09 02:00:32.2632 INFO 初始化控制器成功
2024-11-09 02:00:32.2632 INFO 正在注册自定义识别器

**Comment by SweetSmellFox** [comment]
试试再pipeline文件夹里面创建一个命名为sample.json的文件，内容为{}

**Comment by P8HT10** [comment]
[maa.log](https://github.com/user-attachments/files/17718993/maa.log)
[2024-11-12.log](https://github.com/user-attachments/files/17718994/2024-11-12.log)
不管用，而且删了重来直接不生成这个这些文件夹了，以上日志是删了重来后的
[maa.bak.log](https://github.com/user-attachments/files/17719165/maa.bak.log)
[2024-11-11.log](https://github.com/user-attachments/files/17719168/2024-11-11.log)
[maa.log](https://github.com/user-attachments/files/17719171/maa.log)

之前第一次用的时候也是空白页，后面从原始（非GUI版本）复制了一份config.json后就能正常使用了
原地覆盖更新后变成白页了，我从之前版本复制了一份Resource\base\pipeline文件夹过来，也不管用
这次怎么折腾都不管用了

**Comment by MuHei-del** [comment]
最新版仍然未解决

**Comment by MuHei-del** [comment]
> > 最新版仍然未解决
> 
> 可以发一下出问题的包，或者给个下载连接

https://github.com/SweetSmellFox/MFAWPF/releases/tag/1.2.1.9
就是前两天发的这个

**Comment by SweetSmellFox** [comment]
> > > 最新版仍然未解决
> > 
> > 
> > 可以发一下出问题的包，或者给个下载连接
> 
> https://github.com/SweetSmellFox/MFAWPF/releases/tag/1.2.1.9 就是前两天发的这个

要的是带资源文件的，而不是我发的空包

**Comment by MuHei-del** [comment]
> > > > 最新版仍然未解决
> > > 
> > > 
> > > 可以发一下出问题的包，或者给个下载连接
> > 
> > 
> > https://github.com/SweetSmellFox/MFAWPF/releases/tag/1.2.1.9 就是前两天发的这个
> 
> 要的是带资源文件的，而不是我发的空包

重新搞了一下 解决了
