### ISSUE TITLE
关于MFAWPF和Windows计划任务的兼容性

### ISSUE THREAD

**Issue by overflow65537** [SweetSmellFox/MFAWPF#56]
在通过GUI设置好后，可以在MFAWPF.exe中手动正常运行，但如果通过任务计划程序启动MFAWPF.exe并令其启动后自动运行脚本，就会在等待模拟器启动时间结束过后跳出链接失败的字样，日志记载如下：

2024-11-30 16:29:24.6481 INFO 正在连接至模拟器......
2024-11-30 16:29:24.8353 INFO
2024-11-30 16:29:24.8353 INFO 正在初始化控制器
2024-11-30 16:29:26.7710 WARN 初始化控制器时发生错误！
2024-11-30 16:29:26.7835 ERROR MaaFramework.Binding.MaaJobStatusException: IMaaController failed to connect to the device. MaaJobStatus cannot be Failed.
System.Object[]
at MaaFramework.Binding.MaaJobStatusExtensions.ThrowIfNot(MaaJobStatus current, MaaJobStatus correct, String message, Object[] args)
at MaaFramework.Binding.MaaAdbController..ctor(String adbPath, String adbSerial, AdbScreencapMethods screencapMethods, AdbInputMethods inputMethods, String config, String agentPath, LinkOption link, CheckStatusOption check)
at MFAWPF.Utils.MaaProcessor.InitializeController()
at MFAWPF.Utils.MaaProcessor.InitializeMaaTasker()
2024-11-30 16:29:26.7835 WARN 初始化控制器时发生错误！
2024-11-30 16:29:26.7835 INFO 连接失败
2024-11-30 16:29:26.7835 INFO 正在停止......
2024-11-30 16:29:26.7835 INFO 已放弃本次任务

原始问题:overflow65537/MAA_Punish/issues/9

**Comment by overflow65537** [comment]
![QQ20241130-221915](https://github.com/user-attachments/assets/c6728474-a68c-424c-8b5f-73e5227246c5)
我测试了一下,也是一样的问题

**Comment by moulai** [comment]
设置计划任务操作的“起始于”为MFAWPF.exe所在目录应该可以解决问题

**Comment by overflow65537** [comment]
> 设置计划任务操作的“起始于”为MFAWPF.exe所在目录应该可以解决问题

解决
